### PR TITLE
Remove race conditions in tests that execute `go` routines

### PR DESCRIPTION
**Pull request by jpmcb**
```
Using a mutex, this patch removes race conditions that
can happen when attempting to increment numbers from
functions that are executed async in go routines.

Signed-off-by: John McBride <jpmmcb@amazon.com>
```

### Description of changes:

Before this patch, I would see intermittent (although rather frequent) off by 1 errors in the tests:

```
--- FAIL: TestPaginatedFilterAvailableUpdatesSuccess (0.00s)
    aws_test.go:151:
                Error Trace:    aws_test.go:151
                Error:          Not equal:
                                expected: 100
                                actual  : 99
                Test:           TestPaginatedFilterAvailableUpdatesSuccess
                Messages:       should wait for each instance
FAIL
FAIL    github.com/bottlerocket-os/bottlerocket-ecs-updater     0.006s
FAIL
```

After some investigation, I found that this is due to a race condition with the following counter:
https://github.com/bottlerocket-os/bottlerocket-ecs-updater/blob/cdaf5f76179428bd83f6f25dac2d35192b9aaea3/updater/aws_test.go#L124

This counter is incremented through the SSM mock:

https://github.com/bottlerocket-os/bottlerocket-ecs-updater/blob/cdaf5f76179428bd83f6f25dac2d35192b9aaea3/updater/aws_test.go#L140-L144

But the problem is that `WaitUntilCommandExecutedWithContextFn` is called from any number of `go` routines that may attempt to increment the variable at the same time resulting in the strange off by 1 errors:

https://github.com/bottlerocket-os/bottlerocket-ecs-updater/blob/cdaf5f76179428bd83f6f25dac2d35192b9aaea3/updater/aws.go#L439-L456

### Testing done:

I now have no flakes occurring and have run the tests through a "fail until" script:
```bash
#!/usr/bin/env bash

echo "Running go tests until fail"
while go test ./... -count=1 -v; do :; done
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]

**Review by markusboehme — APPROVED** [review]
Nice!

It is not obvious why the other functions of the mock don't need any locking. Looking at more of the ECS updater code it seems they're not called concurrently, but that's outside the control of the mock. It might be useful to synchronize mutations to shared state to remove any doubt.

**Comment by jpmcb** [comment]
> It is not obvious why the other functions of the mock don't need any locking. Looking at more of the ECS updater code it seems they're not called concurrently

Right - the `WaitUntilCommandExecutedWithContext` method is the only one that is executed in parallel which isn't obvious from the test code.

> It might be useful to synchronize mutations to shared state to remove any doubt.

I had also considered doing something like that. This is a common pattern in Go code:
```go
type SafeCounters struct {
    mu       sync.Mutex
    counter1 int
    counter2 int
    ...
}
```

where the `SafeCounter` is created and locked in each case but this felt like alot of code to cover one edge in the tests.

---

This probably deserves a comment in the SSM mock to inform the coder that this specific method is executed concurrently in the ECS code paths.

**Comment by jpmcb** [comment]
Force pushed to add a few comments to hopefully make it more clear why the mutexes are needed.

I also am running `golangci-lint` locally and I'm not getting any linter errors. I think we can safely ignore those failures until #107 is merged.

**Comment by markusboehme** [comment]
Agree, the comment seems like a good middle ground. Thanks John!

**Pull request merged**
