### PR TITLE
Use latest bottlerocket-sdk with newest Go version

### PR DESCRIPTION
**Pull request by jpmcb**
**Issue number:**

N/a - related to https://github.com/bottlerocket-os/bottlerocket-sdk/pull/84

**Description of changes:**

Uses latest SDK with newest Go version

**Testing done:**

_Coming soon ..._

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by jpmcb** [comment]
Able to `make test`, `make image`, and `make lint`.

---

Integration tests looks good! This should be good to go!

```
❯ aws logs get-log-events \
  --log-group-name bottlerocket-ecs-updater-integ \
  --log-stream-name $logStreamName \
  --output text | rg "successfully"

...

EVENTS  1668528257790   2022/11/15 16:04:13 i-0743dfc15fa34dce1: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-06d88a6809b49913c: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-0a3e0fff383a2ed7b: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-059db63a50326c297: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-0a50416c48c28627b: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-0c6bc798da6996939: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-07fd3fd22de4156f5: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-07c02e5e9046f49f8: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-089a5a0b68eb7c71c: Instance updated successfully  1668528253710
EVENTS  1668528257790   2022/11/15 16:04:13 i-0c1cd017b526c4d6a: Instance updated successfully  1668528253710

❯ aws logs get-log-events \
  --log-group-name bottlerocket-ecs-updater-integ \
  --log-stream-name $logStreamName \
  --output text | rg "fail"
❯
```

**Review by stmcginnis — APPROVED** [review]
Testing looks good, and nothing changed in the `v0.27.0` to `v0.28.0` bump that I would be too concerned about.

**Comment by jpmcb** [comment]
> and nothing changed in the v0.27.0 to v0.28.0 bump that I would be too concerned about.

Yeah, mostly upgrades to Go 1.19.2 which didn't carry any breaking changes and captures a few CVEs

**Review by zmrow — APPROVED** [review]
:night_with_stars:

**Pull request merged**
